### ISSUE TITLE
send and receive cmd output

### ISSUE THREAD

**Issue by raedah** [raedahgroup/godcr-old#54]
```
[x@rose dcrcli]$ ./dcrcli send
Destination Address:
invalid address

Destination Address:
invalid address

```
Correct msg would be 'You did not specify an address.' and then just exit. 

Otherwise, "That is not a valid address. Try again."
Do not have unneeded blank lines in the output when re-asking the question.

**Comment by raedah** [comment]
Similiar for amount
```
Amount (DCR):
error parsing amount: strconv.ParseFloat: parsing "": invalid syntax
```
You did not specify an amount.' and then just exit. 
"That is not a valid amount. Try again."

**Comment by raedah** [comment]
On success the output looks like this..
```
Amount (DCR): 2.123
Wallet Passphrase:                                      Result | Hash
                                            |
 The transaction was published successfully | b5f844895a4e5b4e496929be0356e8435a8c30976d6bd59a29539fddd37fc9d7
```
better would be
```
Amount (DCR): 2.123
Wallet Passphrase:
You are about to send 2.123 DCR to TsgQwgjtgG7KB68pJwyUAq54uZ6GW1V73dJ
Are you sure? (y/n): y
sent txid b5f844895a4e5b4e496929be0356e8435a8c30976d6bd59a29539fddd37fc9d7
```

**Comment by raedah** [comment]
```
$ ./dcrcli receive
                             Address | QR Code
                                     |
 TsVhcKRQbTGwpVUX1TQJKMPDyTknKRBfkVW |

[Giant QR code]

```
better would be
```
$ ./dcrcli receive
TsVhcKRQbTGwpVUX1TQJKMPDyTknKRBfkVW
[QR code]

```
Lets make the qr code smaller. Smallest usable would be preferred.

**Comment by Jujhar** [comment]
I am working on this.

**Comment by itswisdomagain** [comment]
@Jujhar, one good way to fix this cli output message across the cli package is to do the following:

1. Currently each command handler has this signature
`handler func(walletrpcclient *walletrpcclient.Client, commandArgs []string) (*response, error)`

2. The *response returned from executing each command is printed to stdOut, if there's an error, the error is instead printed to stdErr

If we change the signature of the command handler to
`handler func(walletrpcclient *walletrpcclient.Client, commandArgs []string) error` so that each command can only return an error if there's one, and then each command prints it's own message after successful execution.

That way, each command handler can print it's success message in a way different from others and mustn't be forced to use the same pattern.

What do you think @Jujhar?

**Comment by Jujhar** [comment]
I was just playing around with this thinking about returning &response{} as null with that there is no need to remove all the return nils but this one seems better as returning nothing is better then always returning nil for each of the errors.

**Comment by Jujhar** [comment]
Also there is a bit of an error with that signature related to the code in commands.go file.
